<a href="https://colab.research.google.com/github/Shwetarhonnikoppa/Python/blob/main/python_classwork_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A =17

In [ ]:
a =18

In [ ]:
A

17

In [ ]:
Enter_Password =int(input( "Enter your 4 digit password "))

Enter your 4 digit password 1234


In [ ]:
a1 =18

In [ ]:
a1

18

In [ ]:
Virat_Kohli = 100
Virat_Kohli

100

In [ ]:
b = "100"

In [ ]:
type(b)

str

In [ ]:
b=2

In [ ]:
type(A)

int

In [ ]:
A =18
B =20

In [ ]:
B=A

In [ ]:
print(B)

18


#Single Value Assignment
#Multiple Value Assignment

In [ ]:
Name='victor'

In [ ]:
salary=2000

In [ ]:
Address ="Bangalore"

In [ ]:
print(Name)
print(Address)

victor
Bangalore


In [ ]:
Name

'victor'

In [ ]:
name = 'cena'

In [ ]:
name

'cena'

In [ ]:
x=y=z =10

In [ ]:
y

10

In [ ]:
x , y, z = 10,15,20

In [ ]:
Class ="Python Batch"

In [ ]:
Class.lower()

'python batch'

In [ ]:
Class.upper()

'PYTHON BATCH'

In [ ]:
Class='Python1'

In [ ]:
_Class='python class'

In [ ]:
Class.title()

'Python1'

In [ ]:
Class.capitalize()

'Python1'

In [ ]:
Class.swapcase()

'pYTHON1'

In [ ]:
Class.isalpha()

False

In [ ]:
Class.isalnum()

True

In [ ]:
Class.isnumeric()

False

In [ ]:
Class.startswith("P")

True

In [ ]:
A = "Machine2024"

In [ ]:
A.isalpha()

False

In [ ]:
A.isalnum()

True

In [ ]:
A.isnumeric()

False

In [ ]:
C = "    data science   "
print(C)

    data science   


In [ ]:
C.endswith("c")

False

In [ ]:
C.startswith("d")

False

In [ ]:
C.split()   # Devides based on space

['data', 'science']

In [ ]:
a ="+91-5674982023"

In [ ]:
#a.split()
a.split("5")

['+91-', '674982023']

In [ ]:
C.split("a")

['    d', 't', ' science   ']

In [ ]:
a="Data Science \n Machine Learning"
print(a)
a.splitlines()

Data Science 
 Machine Learning


['Data Science ', ' Machine Learning']

In [ ]:
C.strip()  # Used for formatting of the data   "   Vyankat   "

In [ ]:
C.lstrip()

In [ ]:
C.rstrip()

'    data science'

In [ ]:
a="data"    #4 char
a.center(13,"*")

'*****data****'

In [ ]:
print(a.rjust(10,"*"))
a.ljust(10,"*")

******data


'data******'

In [ ]:
a.index("t")  # it will give us the 1st occurance
#data

2

In [ ]:
#Join is used to merge strings

#E.g:

"d".join("abc")

In [ ]:
"da".join("data sceince")

In [ ]:
X = "Data Science"
X.count("a",3)

In [ ]:
# Concatenation of Operators

x =" Data"
y="Science"

In [ ]:
x+y

In [ ]:
x+" "+y

In [ ]:
x= "DataScience"
#extract Dace


In [ ]:
x[0:2]

In [ ]:
x = "Machine Learning"

In [ ]:
#Print MALE
#MANE ear
print(x[0:2].upper()+x[5:7].upper()+" " +x[9:12])

x[ :2].upper()+x[8:10].upper()

MANE ear


'MALE'

In [ ]:
x[-2: ]

In [ ]:
(x[0:2]+x[-2: ]).upper()

In [ ]:
X = ['data',9,'2024.23',3+4j,[10,20,30]]

X[-3][-3: ]

'.23'

In [ ]:
print(X)

['data', 9, 2024.23, (3+4j), [10, 20, 30]]


In [ ]:
X[0][0:2]
#print .23
print(x[2][4: ])

In [ ]:
#X[2][4: ]
X[-3][-3: ]

'.23'

In [ ]:
X[-5][-2: ]

'ta'

In [ ]:
len(X)
topics[0][1][1][0:3]

'Cal'

In [ ]:
topics = [
    ['Math', ['Algebra', 'Calculus', 'Geometry']],
    ['Science', ['Physics', 'Chemistry', 'Biology']],
    ['Technology', ['Programming', 'Networking', 'AI']],
    ['History', ['Ancient', 'Medieval', 'Modern']],
    ['Art', ['Painting', 'Sculpture', 'Architecture']]
]


In [ ]:
#print Modern Architecture
topics[3][1][-1]+" "+topics[4][1][2]

'Modern Architecture'

In [ ]:
#print GEO, BIO, CHEM

topics[0][1][2][0:3].upper()+","+topics[1][1][2][0:3].upper()+","+topics[1][1][1][0:4].upper()

'GEO,BIO,CHEM'

In [ ]:
topics[0][1][2][0:3].upper() +","+topics[1][1][2][0:3].upper()+ ","+topics[1][1][1][0:3].upper()

'GEO,BIO,CHE'

In [ ]:
x =1
print(x)

1


In [ ]:
x=int(input("Enter value of X  "))

Enter value of X  100


In [ ]:
type(x)

int

In [ ]:
#Data types in Python:
#1.Immutable Data type
#2.Mutable data type

#Immutable Data Type:
#i. Numeric Data
#ii.String
#iii.tuple

#Mutable Data Type:
#i.List
#ii. Dictionary

#i.Numeric Data Type:
#1.Integer  #2.Float   3.Complex

#1.Integer:this value is represented by int class.
#interger contains +v-0--ve i.e.whole numbers
#in python there is no limit how long an interger value be

X= 15
type(x)
y=int(input("Assign value to Y"))

#2.Float: This value is represented by decimal point.

Assign value to Y76.5


ValueError: invalid literal for int() with base 10: '76.5'

In [ ]:
x = -150005464646198465184646198494564
print(x)
type(x)

-150005464646198465184646198494564


int

In [ ]:
w=66.5
print(w)
type(w)


66.5


float

In [ ]:
w = float(input("Give a Decimal Values: "))

Give a Decimal Values: 25


In [ ]:
c=66.5

In [ ]:
#Complex : n + ij

b =5+4j

type(b)

complex

In [ ]:
type(c)

In [ ]:
#Complex numeric data type:
#It is represented by the complex class
#It is specified as (real part)+(imaginary part)j
#E.g
x=3j
y=5+45j
w=-3+6j

In [ ]:
type(x)

complex

In [ ]:
y=-2+3j

In [ ]:
type(y)

In [ ]:
a = 5
print("Type of a: ", type(a))

b = 5.0
print("\nType of b: ", type(b))

c = 2 + 4j
print("\nType of c: ", type(c))

In [ ]:
#2.String:A string is a collection of one or more characters
#it can be represetnd by using Single quote(''),double quote("")
#or tripple quote
#Single Quote:

String1 = "'Welcome to the World of Python'"
print(String1)
type(String1)


'Welcome to the World of Python'


str

In [ ]:
#Double Quote:

String2 = "I'm a Python Code"
print("\nString with the use of Double Quotes: ")
print(String2)
print(type(String2))



String with the use of Double Quotes: 
I'm a Python Code
<class 'str'>


In [ ]:
#Tripple Quote:

String3 = '''I'm a Code and I live in a world
of Programmer'''
print("\nString with the use of Triple Quotes: ")
print(String3)
print(type(String3))



SyntaxError: unterminated string literal (detected at line 3) (<ipython-input-88-6b12caef6401>, line 3)

In [ ]:
#Creating a Multiline String

String4 = '''
            Python
            For
            Coders
            '''
print("\nCreating a multiline String: ")
print(String4)


Creating a multiline String: 

            Python 
            For 
            Coders
            


In [ ]:
'''
            Python
            For
            Coders
            '''

'\n            Python\n            For\n            Coders\n            '

In [ ]:
#Slicing Of Strings:

print(String1)
print("\nFirst character of string is: ")
print(String1[0])

Welcome to the World of Python

First character of string is: 
W


In [ ]:
print("\n Last character of string: ")
print(String1[-1])


 Last character of string: 
n


In [ ]:
print(String1)
print(String1[2])

Welecome to the World of Python
l


In [ ]:
print(String1[15:21])

 World


In [ ]:

print(String1[ :7:1])

Welcome


In [ ]:
print(String1)

Welecome to the World of Python


In [ ]:
str = "Welcome to the Python Technology"

In [ ]:
str[4:-2]

In [ ]:
# W e l c o m e   t o    t   h  e    P   y  t  h  o  n     T  e  c  h  n  o  l  o  g  y
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15  16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
                                                                  .... -5  -4  -3 -2  -1

In [ ]:
print(str[22:32])        #32 =32-1 =31

print(str[11:14])

print(str[11:14:1])

print(str[22:32:2])

print(str[0 : 32 :3])
print(str)

print(str[0:32])

print(str[ : ])

print(str[15: ])

In [ ]:
# Print Python
print(str[15:21:1])  #21=21-1

In [ ]:
#skip 1 char altrenatively:
print(String1[ 0: 32:2])

In [ ]:
print(str[ : :2])

In [ ]:
string='I am Vyankat'

In [ ]:
# I   a m   V  y  a  n  k  a  t
# 0 1 2 3 4 5  6  7  8  9  10 11
                           -2 -1

In [ ]:
print(string[0])

In [ ]:
print(string[0:8:1])

In [ ]:
print(string[ :8:1])

In [ ]:
print(string[ : ])

In [ ]:
# I   a m   V  y  a  n  k  a  t
# 0 1 2 3 4 5  6  7  8  9  10 11
  #                         -2 -1
#Reverse Slicing

string[8:1:-2]

In [ ]:
S ="Data Science"

In [ ]:
S[5: ]

'Science'

In [ ]:
S[0:4]

'Data'

In [ ]:
S[ : ]

'Data Science'

In [ ]:
S[0:100]

'Data Science'

In [ ]:
#To Replace String

alphabets =('a,b,c,d,e,f,g,h')

In [ ]:
alphabets.replace('b','a')

In [ ]:
#Tuple:Immutable data type enclosed by()

Weekdays=('Sun','Mon','Tue','Wed','Thu','Fri','Sat')

type(Weekdays)

Weekdays

('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat')

In [ ]:
Weekdays.replace('Sun','Sat')

In [ ]:
type(Weekdays)

tuple

In [ ]:
Weekdays.append('Mercury')

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
Weekdays[0:3]

('Sun', 'Mon', 'Tue')

In [ ]:
Weekdays[0]='Mon'

In [ ]:
Weekdays[1:5]

('Mon', 'Tue', 'Wed', 'Thu')

In [ ]:
Weekdays.append('Mercury')

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
#List: Allows us to make changes and eclosed by []
#List can contain different data types

Salaries=[10,15,20]
Salaries

Salaries[0:3]

[10, 15, 20]

In [ ]:
type(Salaries)

list

In [ ]:
#We can make changes in list, lets change 1st salary from 10 to 18.
Salaries[0]=18

In [ ]:
Salaries

[18, 15, 20]

In [ ]:
#If we want to increase the salary of 3rd person by 8
#Salaries[2]=28
Salaries[2]+=8

In [ ]:
Salaries

[18, 15, 28]

In [ ]:
Salaries[2]=40

Salaries

[18, 15, 40]

In [ ]:
#To add the data in List
#Use .append

Salaries.append(28)

In [ ]:
Salaries

[18, 15, 40, 28]

In [ ]:
#We can store another list inside the list:
#This is called as nested list

Mixed_List=[1,'a',1.5]
print(Mixed_List)

[1, 'a', 1.5]


In [ ]:
#Create A string by your name and slice it
#create a tuple
#create a list

In [ ]:
Mixed

[1, 'a', 1.5]

In [ ]:
Mixed=[1,'a',1.5,[155,'b']]

In [ ]:
Mixed

[1, 'a', 1.5, [155, 'b']]

In [ ]:
#Even we can Add tuple inside a List:

Mixed_List=[1,'a',1.5,[155,'b'],(88,777)]
      #      0  1   2      3         4

In [ ]:
print(Mixed_List[4:0:-1])

In [ ]:
#Indexing would be like
#[1,'a',1.5,[155,'b'],(88,777)]
# 0  1   2      3         4

type(Mixed[0])

int

In [ ]:
str='String slicing in python'

In [ ]:
#Q.1 Print 'slicing' in output
#Q.2 Print 'nhyi'

print(str[7:15])
print(str[-1:-10:-2])

#Tuple :
- Tuple is a immutable data type and enclosed in ( )


In [ ]:
Weekdays =('Sun','Mon','Tue','Wed','Thu','Fri','Sat')

In [ ]:
Weekdays

('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat')

In [ ]:
type(Weekdays)

tuple

In [ ]:
Weekdays[0]='Mon'

In [ ]:
#Weekdays =("'Sun','Mon','Tue','Wed','Thu','Fri','Sat'")

In [ ]:
type(Weekdays)

In [ ]:
Weekdays.append['mercury']

# Dictionary
Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.

Dictionaries are written with curly brackets, and have keys and values:





In [ ]:
#Dictinary: It allows to create key Value pairs.
# e.g: If we want to associate person's name with person's salaries.
salaries={'John':15, 'Jane':14, 'Johny': 16}
      #         0          1            2

In [ ]:
salaries

{'John': 15, 'Jane': 14, 'Johny': 16}

In [ ]:
salaries['John']

#salaries[15]

15

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [ ]:
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [ ]:
print(len(thisdict))

3


In [ ]:
#Dictionary Items - Data Types
#The values in dictionary items can be of any data type:

#Example
#String, int, boolean, and list data types:

thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}


The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [ ]:
print(thisdict)

{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': ['red', 'white', 'blue']}


In [ ]:
'''The dict() Constructor
It is also possible to use the dict() constructor to make a dictionary.

Example
Using the dict() method to make a dictionary:
'''
thisdictionary = dict(name ="John", age = 36, country = "Norway")
print(thisdict)



{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': ['red', 'white', 'blue']}


# Python Operators
#Operators are used to perform operations on variables and values.

#In the example below, we use the + operator to add together two values:


In [ ]:
x=5
y=2
print(x*y)

7


In [ ]:
print(105+5)

110


# Python divides the operators in the following groups:

1. Arithmetic operators
2. Assignment operators
3. Comparison operators
4. Logical operators
5. Identity operators
6. Membership operators
7. Bitwise operators

#Arithmetic operators are used with numeric values to perform common mathematical operations:

# Operator	Name	Example
+	Addition	x + y
-	Subtraction	x - y
*	Multiplication	x * y
/	Division	x / y
%	Modulus	x % y
**	Exponentiation	x ** y
//	Floor division	x // y


In [ ]:
x = 50
y = 10
addition = x + y
print(f"Addition: {x} + {y} = {addition}") #Printed O/P using formatted string
#print(addition)

#f' string:
#print("6 + 5:", addition)

Addition: 50 + 10 = 60


In [ ]:
x = 5
y = 3

print(x+y)

8


In [ ]:
#Subtraction (-): Subtracts the second number from the first.
subtraction = x - y
print(f"Subtraction: {x} - {y} = {subtraction}")



In [ ]:
print("Substraction of x and y=",x-y)

In [ ]:
#Multiplication (*): Multiplies two numbers.

multiplication = x * y
print(f"Multiplication: {x} * {y} = {multiplication}")



In [ ]:
x*y

In [ ]:
#Division (/): Divides the first number by the second.
x= 15
y= 4
division = x / y
print(division)
print(f"Division: {x} / {y} = {division}")

#Take any two numbers and perform addition, subtraction, multiplication and division

3.75
Division: 15 / 4 = 3.75


In [ ]:
print(x/y)
type(x/y)

In [ ]:
a =20
b =10

In [ ]:
#Modulus (%): Returns the remainder of the division of the first number by the second.
x= 15
y= 4
modulus = x % y    #Remainder
print(f"Modulus: {x} % {y} = {modulus}")



In [ ]:
#Exponentiation : First number will be base and second number will be power of the first

a =6
b=3
c =12
d=4

expn = b**a
print(expn)

In [ ]:
#Exponentiation (**): Raises the first number to the power of the second.
x= 5
y= 3

#5^3

exponentiation = x ** y
print(f"Exponentiation: {x} ** {y} = {exponentiation}")

#5*5*5

In [ ]:
#Floor Division (//): Divides the first number by the second and returns the closest integer less than or equal to the result.
x= 13
y= 4
division = x/y
floor_division = x // y
print(f"Floor division: {x} // {y} = {floor_division}")
print(division)

Floor division: 13 // 4 = 3
3.25


In [ ]:
a = 40
b = 5



In [ ]:
a=9
b=4

fl_di=a//b
print(fl_di)

#take any two variables and find modulus, expn, floor division

2


# Python Assignment Operators
Assignment operators are used to assign values to variables:
Operator	Example	   Same As
=	         x = 5	   x = 5
+=	       x += 3	   x = x + 3
-=	       x -= 3	   x = x - 3
*=	       x *= 3	   x = x * 3
/=	       x /= 3	   x = x / 3
%=	       x %= 3	   x = x % 3
//=	       x //= 3	   x = x // 3
**=	       x **= 3	   x = x ** 3
&=	       x &= 3	   x = x & 3
|=	       x |= 3	   x = x | 3
^=	       x ^= 3	   x = x ^ 3
>>=	       x >>= 3	   x = x >> 3
<<=	       x <<= 3	   x = x << 3
:=	       print(x := 3)	x = 3
                            print(x)

In [ ]:
# = Assignment:

x=10

x = 5

print(x)

5


In [ ]:
# += Addition Assignment:
x+= 3  #x=x+3  #x =5+3
print(x)


In [ ]:
# -= Subtraction Assignment:
x-=3    #x = x -3  #8-3
print(x)

In [ ]:
# *= Multiplication Assignment:
x*=3   #x = x * 3  #5*3
print("Value of x:",(x))

In [ ]:
# /= Division Assignment:
x /= 3  # x=x/3  #15/3
print(x)


In [ ]:
# %= Modulus Assignment:
x%= 3  # x = X % 3  #5%3
print(x)

# //= Floor division
y= 16
y //= 5   #y= y//5

print(y)

#Take any variable and perform assignments operations.

2.0
3


In [ ]:
# &= Bitwise AND Assignment:
#& is the bitwise AND operator, which compares each bit of two numbers and returns a new number.
#Each bit in the result is 1 if the corresponding bits in both operands are 1, otherwise the bit is 0.
# 1   0   0
# 1   1   1
# 0   1   0
#1    1    1
x = 5  #  0101
x &= 3  # 0011; Equivalent to x = x & 3
print(x)  #0001
bin(x)

y = 6

y &=4

print(y)

bin(y)

#bin(26)

1
4


'0b100'

In [ ]:
bin(6)

bin(8)

bin(1)

'0b1'

In [ ]:
a =5  #0101
b =6  #0110

c =a & b  #0100

print(c)
bin(c)

4


'0b100'

#Bitwise OR (|) Operation
The bitwise OR operation compares each corresponding bit in the binary representation of two numbers. The result of each comparison is 1 if either of the bits is 1, and 0 only if both bits are 0.

Here’s the truth table for a bitwise OR operation:

Bit 1	Bit 2	Result
0	 0 =	0
0	 1 =  1
1	 0 =	1
1	 1 =	1
In other words:

1 | 0 results in 1.
0 | 1 results in 1.
1 | 1 results in 1.
0 | 0 results in 0.

In [ ]:
x = 5  # 0101
x |= 3  #0011; Equivalent to x = x | 3
print(x)  #(0111)
bin(x)

7


'0b111'

In [ ]:
a = 7   #111
a |=10  #1010

print(a)
bin(a)
a = 7   #111
a &=10  #1010

print(a)
bin(a)




15
2


'0b10'

#Understanding Bitwise XOR (^) Operation
In a bitwise XOR operation, each bit in the LHS binary number is compared with the corresponding bit in the RHS binary number. The XOR operation will return 1 if the bits are different and 0 if the bits are the same.

Here's the truth table for a bitwise XOR operation:

Bit1	Bit2	Result
0	     0	  0
0 	   1	  1
1	     0	  1
1	     1	  0
So:

1 ^ 0 results in 1
0 ^ 1 results in 1
1 ^ 1 results in 0
0 ^ 0 results in 0

In [ ]:
x = 5  # 0101
x ^= 3  # 0011; Equivalent to x = x ^ 3
print(x)
bin(x)  # (0110)


6


'0b110'

In [ ]:
a = 8
a^=2
print(a)
bin(a)

#The >>= (right shift assignment)
- operator shifts the bits of the left-hand side (LHS) variable to the right by the number of positions specified by the right-hand side (RHS) value, then updates the LHS variable with the shifted result.

#How Right Shift Works
- In a right shift, each bit in the binary representation of the number is moved to the right by the specified number of positions. The empty positions on the left are filled with 0s (for positive numbers), and the bits shifted out of the right end are discarded. Essentially, right-shifting by n bits divides the number by 2^n, discarding any remainder.

#Truth Table Explanation
- There isn't a truth table for the right shift operation in the same sense as for logical or bitwise operations. Instead, it’s helpful to see how each bit moves when we apply a right shift:

- Example: Shifting x = 8 (binary 1000) to the Right by 1, 2, and 3 Positions
- Operation	Binary Before Shift	Shift Amount	Binary After Shift	Decimal - After Shift
x >> 1	1000	1	0100	4
x >> 2	1000	2	0010	2
x >> 3	1000	3	0001	1

In [ ]:
x = 8  # 1000
x >>= 2  # Equivalent to x = x >> 2
print(x)  # (0010)


y =10 #1010

y>>=3  #0001
print(bin(y))
print(y)

2
0b1
1


In [ ]:
x = 16  #10000

x>>=2   #00100

print(x)
print(bin(16))
bin(4)

4
0b10000


'0b100'

#The <<= (left shift assignment)
- operator shifts the bits of the left-hand side (LHS) variable to the left by the number of positions specified by the right-hand side (RHS) value, then updates the LHS variable with the shifted result.

# How Left Shift Works
- In a left shift operation, each bit in the binary representation of a number is moved to the left by the specified number of positions. Empty positions on the right are filled with 0s, and the left shift effectively multiplies the number by 2^n, where n is the number of positions shifted.

#Truth Table Explanation
- Like the right shift, the left shift operation doesn’t have a traditional truth table. Instead, it is useful to look at how each bit moves when a left shift is applied.

- Example: Shifting x = 3 (binary 0011) to the Left by 1, 2, and 3 Positions
- Operation	Binary Before Shift	Shift Amount	Binary After Shift	Decimal
 # After Shift
x << 1	0011	1	0110	6
x << 2	0011	2	1100	12
x << 3	0011	3	1000	24
- In each case, the bits are shifted left by the specified amount, and 0s are added to the right to fill in the positions.

In [ ]:
x = 3  # 0011
x <<= 2  # Equivalent to x = x << 2
print(x)  # (1100)
x>>=2

print(x)

12
3


#The := operator
- known as the Walrus Operator or Assignment Expression, was introduced in Python 3.8. It allows assignment of a value to a variable as part of an expression, which can be useful for simplifying certain types of code, such as within if statements or while loops. The assignment expression evaluates to the assigned value, making it possible to use the value immediately in an expression.

# Understanding the Walrus Operator
- The Walrus Operator (:=) is different from traditional assignment (=) because it allows you to assign a value to a variable within an expression, without needing a separate line. This is especially useful in conditional expressions where you want to both assign a variable and check its value.

In [ ]:
# :=
#The walrus operator := assigns a value to a variable as part of an expression (introduced in Python 3.8).

In [ ]:
print(x := 3)  # Assigns 3 to x and prints it
print(x)


3
3


# Python Comparison Operators
Comparison operators are used to compare two values:

Operator	Name	      Example
==	      Equal	      x == y  # x=5 , y=7 -->False
!=	     Not equal	  x != y	#x=5 , y=5 -->False   <>
>	      Greater than	x > y	#x=5, y=3  --> True
<	      Less than	    x < y	#x=5 , y= 3--> False
>=	   Greater than or equal to	 x >= y	 #x=5, y=5 -->True
<=	  Less than or equal to	  x <= y    # x=5, y=3 -->False



In [ ]:
x = 15
y = 20

x>=y

False

# Python Logical Operators
Logical operators are used to combine conditional statements:
Operator	Description	                                    #Example
- and 	    Returns True if both statements are true	    x < 5 and  x < 10    #x=4  -->True
- or	        Returns True if one of the statements is true,	x < 5 or x < 4  #x = 4
- not	        Reverse the result, returns False if the result is true	not(x < 5 and x < 10)

In [ ]:
#and 	    Returns True if both statements are true
#e.g:

a = 5
b = 10

print(a > 2 and b < 15)
print(a > 2 and b < 8)

print(a > 2 or b < 15)
print(a > 2 or b < 8)

print(not(a > 2 or b < 8))

True
False
True
True
False


In [ ]:
#not	Reverse the result, returns False if the result is true	not
#e.g:

a = 5
b = 10

print(not (a > 2))  #False
print(not (a > 6))  #True

# Python Identity Operators
Identity operators are used to compare the objects, not if they are equal, but if they are actually the same object, with the same memory location:

Operator  Description	                                                                    Example
- is 	      Returns True if both variables are the same object  memory	                x is y
- is not	  Returns True if both variables are not the same object memory	            x is not y

In [ ]:
a = [1, 2, 3]   #object memory location 1
b = a           # 1
c = [1, 2, 3]   #Object memory location  2
d = c           #2
print(a is b)    #  True
print(a is c)    #False
print(c is not d)  #False


True
False
False


In [ ]:
#is not	  Returns True if both variables are not the same object in the memory
#e.g:

a = [1, 2, 3]   #1
b = a           #1 memory location
c = [1, 2, 3]   #2 memory location

print(a is not b)  #FAlse
print(a is not c)  #True

False
True


In [ ]:
#cached Range in python(-5 to 256)
x = 10    #1 1 byte
y = 10    #
z = 10   #1
b = 157   #2 1 byte
h = 157  #
z =157   #2
j = -4  #3
i=-4    #3

u = 258   #4
i = 258   #5

print(b is h)

a = 257  #1
d = 257  #2


print(a is b)


In [ ]:
#In Python, small integers are cached to improve performance. This means that Python maintains a pool of commonly
#used small integer objects, and when these integers are needed, Python reuses the existing objects instead of creating new ones.
#This process is known as interning.

#Explanation
#1.Integer Caching

#Range: By default, Python caches integers in the range from -5 to 256. This range may vary slightly depending
#on the implementation of Python (like CPython).

#2.Reusability: When you create an integer within this range, Python checks if an identical integer object already exists.
#If it does, Python reuses the existing object. This means that any variable assigned an integer value within this range
#will reference the same memory location.

# Python Membership Operators
Membership operators are used to test if a sequence is presented in an object (such as a string, list, tuple, set, or dictionary).

Operator	Description	                                                                    #Example
- 1.in 	        Returns True if a sequence with the specified value is present in the object	    x in y
- 2.not in	    Returns True if a sequence with the specified value is not present in the object	x not in y


In [ ]:
#in 	Returns True if a sequence with the specified value is present in the object
#Example 1: Checking Membership in a List

fruits = ['apple', 'banana', 'cherry']
print('banana' in fruits)   #True
print('grape' in fruits)    #False


In [ ]:
#Example 2: Checking Membership in a String

text = "Hello, world!"
print('H' in text)
print('hello' in text)


In [ ]:
#Example 3: Checking Membership in a Dictionary

person = {'name': 'Alice', 'age': 25}
print('name' in person)  # Output: True
print('Alice' in person) # Output: False
print('age' in person)


In [ ]:
#The not in operator returns True if the specified value is not found in the sequence, otherwise it returns False.
#Example 1: Checking Non-Membership in a List

fruits = ['apple', 'banana', 'cherry']
print('grape' not in fruits)  # Output: True
print('banana' not in fruits) # Output: False


# Python Bitwise Operators
Bitwise operators are used to compare (binary) numbers:

Operators  Operations
    &        AND
    l        OR
    ^	     XOR
    ~	     NOT
   <<	 Zero fill left shift
   >>	 Signed right shift
    

In [ ]:
my_dict = {'a': 2, 'b': 3, 'a': 5}
print(my_dict['a'])


5


# 1. AND (&)
It compares each bit of two numbers and Sets each bit to 1 if both bits are 1.


In [ ]:
a = 5          # 0 1 0 1
b = 3          # 0 0 1 1
result = a & b # 0 0 0 1
print(result)
print(bin(5))

1
0b101


In [ ]:
b=int('0001', 2)
b

1

In [ ]:
a = 12  # 1100
b = 10  # 1010
result = a ^ b  # 0110
print(result)

&, |, ^, ~, <<, >>

6


# OR (|):
Sets each bit to 1 if one of two bits is 1.


In [ ]:
a = 5   # 0101
b = 3   # 0011
result = a | b  # 0111
print(result)


7


# XOR (^):
Sets each bit to 1 if only one of two bits is 1.
    
    

In [ ]:
a = 5   # 0101
b = 3   # 0011
result = a ^ b  # 0110
print(result)


6


# NOT (~):
Inverts all the bits.
    

In [ ]:
a = 5  # 0101
result = ~a  # 1010 (in 2's complement form, this is -6)
print(result)


-6


# Left Shift (<<):
Shifts bits to the left, filling with zeros.



In [ ]:
a = 5  # 0101
result = a << 2  # 1010
print(result)
bin(result)[2:]

# 0101 << 10100


20


'10100'

In [ ]:
b=int('10101',2)
b

21

In [ ]:
b=21  #0101
result=b<<2
print(result)
bin(result)[2:]

84


'1010100'

In [ ]:
a = 3  # 0011
result = a << 2  # 1100
print(result)
#0011 << 1100

12


In [ ]:
a = 12  # 0b1100
result = a << 2  # 0b1100
print(result)
bin(result)


48


'0b110000'

# Right Shift (>>):
Shifts bits to the right, filling with the zeros (for unsigned types).



In [ ]:
a = 5  # 0101
result = a >> 2  # 0001
print(result)


1


In [ ]:
a = 2 # 0b0010
result = a >> 2
print(result)
bin(result)


0


'0b0'

# How to convert Numbers into Binary:



In [ ]:
bin(20)

'0b10100'

In [ ]:
#To convert Numbers into Binary :

#bin()

a = 25
bin(a)

print(bin(a)[2:])



11001


In [ ]:
b = 82
bin(b)[2:0]
print(bin(b)[2:])

1010010


In [ ]:
print(f"Binary of {b} is {print(bin(b)[2:0])}")


Binary of 82 is None


In [ ]:
#How to convert Binary into Decimals

a = int('1010010' ,2)
print(a)

In [ ]:
# convert 1 0 0 0 1 1 1 into decimal

b =int('1000111',2)
print(b)

71


In [ ]:
#Math Module:

Math Module:

In [ ]:
import math

In [ ]:
math.ceil(3.1)

In [ ]:
math.floor(2.9)

In [ ]:
math.sqrt(4)

2.0

In [ ]:
math.pow(2,1/2)

1.4142135623730951

In [ ]:
print(math.pow(2,4))
print(math.ceil(2.1))

16.0
3


In [ ]:
math.pow(2,-2)

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.e

2.718281828459045

In [ ]:
math.tau

6.283185307179586

In [ ]:
math.trunc(100.1)

100

In [ ]:
math.fabs(-7)

7.0

In [ ]:
math.exp(2)    #e^x

7.38905609893065

In [ ]:
#math.log(x, base)

math.log(8,2)

3.0

In [ ]:
math.factorial(5)    #5*4*3*2*1

120

In [ ]:
math.gcd(40,80)   #greatest common divisor

40

# Python Conditions and If statements

#The if...else statements in Python are used for decision-making.
#They allow your program to execute certain blocks of code based on certain conditions.
#Let's explore the different forms of if...else statements with detailed explanations and examples.

In [ ]:
#Basic if Statement
#The basic if statement executes a block of code if a specified condition is true.

Tomato = 15
if Tomato <=10:
    print("Bring 1kg of tomatoes")

#Indentation
#Python relies on indentation (whitespace at the beginning of a line) to define scope in the code.
#Other programming languages often use curly-brackets for this purpose.{}



In [ ]:
Tomato = 15
if Tomato <=20:
    print("Bring 1kg of tomatoes")




Bring 1kg of tomatoes


# Key Points About Indentation in Python
1. Consistency:
Indentation must be consistent within a block of code.
The standard practice is to use 4 spaces per indentation level.
Mixing tabs and spaces or varying the number of spaces can lead to syntax errors.

2.Code Blocks:
Indentation is used to define the body of loops (for, while), conditional statements (if, elif, else),
functions (def), classes (class), and other structures.

3.Syntax Requirements:
Python requires a colon (:) at the end of the line introducing a block of code (e.g., after if statements, for loops, function definitions).
The subsequent lines that are indented form the block of code that belongs to the construct.

In [ ]:
a = 33
b = 200
if b > a:      # : declaration
    print("b is greater than a")


In [ ]:
x=9
if x<10:
  print("Data Science")

In [ ]:

if True:
  print("Data Science")

In [ ]:
if 0:
  print("Data Science")

In [ ]:
if 1:
  print("Data Science")

In [ ]:
x=9
if x%2==1:
  print("Data Science")

Data Science


In [ ]:
x=13
if x//2==6:
  print("Data Science")

In [ ]:
x=int(input())
if (not(x%2==0) and (x<10)):
  print("Data Science")


50


In [ ]:
y=int(input())
if not(y<10):
  print("Y is not less than 10")

12
Y is not less than 10


# if...else Statement
The if...else statement provides an alternative block of code to execute if the condition is false.

In [ ]:
x = 3
if x >5:
  print("X is gretaer than 5")
else:
  print("X is maller than 5")



In [ ]:
{
   {

   }

}

In [ ]:
Tomato =int(input("Tomatoes Cost Per Kg:\n"))
if Tomato <40:
    print("Bring 5 Kg of tomatoes")
elif Tomato <= 50:
    print("Bring 2 kgs of tomatoes ")

else:
    print("Bring 1/2 Kg of tomatoes")

Tomatoes Cost Per Kg:
60
Bring 1/2 Kg of tomatoes


In [ ]:
x = " Data Science"
if "dxt" not in x:
  print("Data")
else:
  print("Science")

Data


In [ ]:
age=int(input())
has_permission=True
if age>=18:
  if has_permission:
    print("Allowed")
  else:
    print("Not Allowed")
else:
  if age>=13:
    print("Allowed with Guardian")
  else:
    print("You are not allowed")

15
Allowed with Guardian


In [ ]:
marks=int(input())
if marks<35:
  print("Fail")
elif marks>=35 and marks<50:
  print("Grade C")
elif marks>=50 and marks<75:
  print("Grade B")
elif marks>=75 and marks<90:
  print("Grade A")
else:
  print("Grade A+")

65
Grade B


# Elif
The elif keyword is Python's way of saying "if the previous conditions were not true, then try this condition".

In [ ]:
Tomato =int(input("Tomatoes Cost Per Kg:\n"))
if Tomato <30:
    print("Bring 2 Kg of tomatoes")
elif Tomato <40:
    print("Bring 1 kgs of tomatoes")
else:
    print("1/2 Kg of tomatoes")

In [ ]:
a = 33
b = 33
if b > a:
    print("b is greater than a")
elif a < b:
    print("a is less than b")
else:
    print("a is equal to b")

In [ ]:
a = int(input("Enter a Value For a:\n"))
b = int(input("Enter a value For b:\n"))
if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")
else:
    print("a is greater than to b")


4# if...elif...else Statement
The if...elif...else statement allows multiple conditions to be checked sequentially.

In [ ]:
x = 7
if x > 10:
    print("x is greater than 10")
elif x > 5:
    print("x is greater than 5")
else:
    print("x is 5 or less")


In [ ]:
Name =input()

if Name =="Rahul":
  print("Welcome Rahul")
elif Name == "Sanju":
  print("Welcome Sanju")
else:
  print("What's your name ?")


# Nested if Statements
if statements can be nested inside other if statements to check multiple conditions.

In [ ]:
x = int(input("Enter a value for x:\n"))     #15
if x > 10:
    print("x is greater than 10")
    if x > 20:
        print("x is also greater than 20")
    else:
        print("x is not greater than 20")
else:
    print("x is 10 or less")


Enter a value for x:
30
x is greater than 10
x is also greater than 20


In [ ]:
#Example with Multiple Conditions
#Let's see a more complex example involving multiple conditions and
#different blocks of code being executed based on the conditions.

x =int(input("Enter a value for x:\n"))   #\n = new line
if x < 0:
    print("x is negative")
elif x == 0:
    print("x is zero")
elif 0 < x <= 10:     # 0 to 10
    print("x is between 0 and 10")
elif 10 < x <= 20:     #10 to 20
    print("x is between 10 and 20")
else:
    print("x is greater than 20")


Enter a value for x:
27
x is greater than 20


In [ ]:
#Conditional Statements by using AND, OR Operaters:

#E.g:Test if a is greater than b, AND if c is greater than a:

a=10
b=7
c=12

if a>b or c>a:
    print("Both Conditions are true")

Both Conditions are true


# The 'pass' Statement
if statements cannot be empty, but if you for some reason have an if statement with no content,
put in the pass statement to avoid getting an error.

In [ ]:
a = 33
b = 200

if b > a:
    pass

In [ ]:
#Exercise:
#Print "I understood Conditional statements" if a is greater than b.

# Python Loops:
#In Python, loops are used to repeat a block of code multiple times.
#There are two main types of loops in Python: for loops and while loops.

# 1. for Loops
A for loop is used to iterate over a sequence (such as a list, tuple, dictionary, set, or string)
and execute a block of code for each item in the sequence.

In [ ]:
purpose: to naviagate through a sequence

In [ ]:
numbers = [1,'a', 2,'b', 3, 4, 5]

for num in numbers:
    print(num, end='')
#print(numbers)

1a2b345

In [ ]:
"datas"

'datas'

In [ ]:
for i in "datas":
  print(i+"*", end=",")

In [ ]:
for i in "20":
  print(i)

2
0


In [ ]:
for i in [1,2,3,4,5]:
  print(i*10,end =',')  #\n- new line

10,20,30,40,50,

In [ ]:
for i in [1,2,3,4,5]:
  print(i+10,end ='\t')   #t - backslash tab

11	12	13	14	15	

In [ ]:
for i in [1,2,3,4,5]:
  print(i+10,end =',')

In [ ]:
for i in [5,4,3,2,1]:
  print(i*"*")   #Pattern Programming,

In [ ]:
n = 5  # Number of rows for the upper half

# Upper part of the diamond
for i in range(1, n + 1):
    print(("*" * (2 * i - 1)).center(2 * n - 1))

# Lower part of the diamond
for j in range(n - 1, 0, -1):  #range(4,0,-1) --> 4,3,2,1
    print(("*" * (2 * j - 1)).center(2 * n - 1))


In [ ]:
n = 5  # Number of rows for the upper half

# Upper part of the diamond
for i in range(1,6):  #1,2,3,4,5
    print(("*" *(2 * i - 1)).center(2 * n - 1))



In [ ]:
data

***DATA***

In [ ]:
for i in [1,2,3,4,5]:
  print(i*"3")

In [ ]:
for i in range(1,101):  #0,1,2,3,4,5,6,7,8,9
  print(i,end=',')


In [ ]:
for i in range(0,10,3):  #step size
  print(i,end=' ')


0 3 6 9 

In [ ]:
for i in range(10,0,-1):  #step size
  print(i,end=',')

10,9,8,7,6,5,4,3,2,1,

In [ ]:
#print even numbers:

for i in range(0,10):
  print(i,end=',') #0,1,2,3,4,5,.....9
  if i%2==0:
    print(i,"is even number")
  else:
    print(i,"is odd number")

In [ ]:
for i in "DATA12345":  #print only DATA
  if i.isalpha()==False:
    print(i,end='')


12345

In [ ]:
for i in "DATA12345":
  if i.isalpha():
    print(i,end=',')

D,A,T,A,

In [ ]:
data ="!@%*$#$,1,2,2,&*@@$#^^#&$&$"
for i in data:
  if i.isalnum()==False:
    print(i,end=" ")


! @ % * $ # $ & * @ @ $ # ^ ^ # & $ & $ 

In [ ]:
*
**
***
****
*****
****
***
**
*

In [ ]:
data ="Data Science Machine Learning"

In [ ]:
x=0
y=len(data)
for i in data:
  x = x+1
  y=y-1
  print(x,y,i)

In [ ]:
#COUNT NUMBER OF CAPITAL LETTERS
a= "data engineering"
a.split()

['data', 'engineering']

In [ ]:
text =''' The Sun emits ~3.8 × 10²⁶ watts of energy! Life depends on its light & heat.
Water (~71% of Earth) supports ecosystems, marine life & weather cycles.
Tech evolves @ rapid speed—AI, IoT & 5G reshape how we work, learn & connect!'''

In [ ]:
text.split()

In [ ]:
for i in text.split():
  if i.isalnum()==True:
    print(i,end=',')



The,Sun,emits,10²⁶,watts,of,Life,depends,on,its,light,Water,of,supports,marine,life,weather,Tech,evolves,rapid,IoT,5G,reshape,how,we,learn,

In [ ]:
for i in text.split():
  if i.isalnum()==False:
    print(i,end=',')

In [ ]:
#Find How many capital letters
x=0
for i in text:
  if i.isupper():
    x=x+1

In [ ]:
x

11

In [ ]:
#Find Capital Letters:
x=0
for i in text:
  if i.isupper():
    x=x+1
    print(i,end=',')

T,S,L,W,E,T,A,I,I,T,G,

In [ ]:
for i in range(0,10):
  print(i,9-i)

In [ ]:
# 9 is lenght of range
for i in range(0,10):
  print(i,len(range(0,10))-1)

In [ ]:
for i in range(1,6):
  print(i*"*")

In [ ]:
#print in reverse order
for i in range(1,6):
  print((6-i)*"*")

In [ ]:
#Print
*
**
***
****
*****
****
***
**
*

In [ ]:
for i in range(1,6):
  print(i*"*")
  if i==5:
    for j in range(5,0,-1):  #Reverse order
       print(j*"*")

In [ ]:
"1213145155"

#ADD ABOVE STRING

In [ ]:
#Example: Iterating Over a String

word = "hello"

for letter in word:
    print(letter)
print(word)

# 2. while Loops
A while loop repeats a block of code as long as a specified condition is true.

In [ ]:
count = 15

while count <= 30:  #condition
    print(count)
    count += 2   # 1,2,3,4,5


In [ ]:
count = 0

while count <= 100:  #condition
    print(count)
    count +=2

In [ ]:
x=2
counter=1

while x<5:
  print("Interation", counter,x)
  counter=counter+1
  x=x+1

  #1,2,3
  #


Interation 1 2
Interation 2 3
Interation 3 4


In [ ]:
x = 1
while x<6:
  print((5-x)*" "+x*"*")
  x+=1




    *
   **
  ***
 ****
*****


In [ ]:
x = 1
while x<6:
  print((6-x)*"*")
  x+=1

In [ ]:
a = 1

while a<=10:
  if(a%2==0):
      print(a ,"is even number")
  else:
      print(a ,"is odd number")
  a+=1

1 is odd number
2 is even number
3 is odd number
4 is even number
5 is odd number
6 is even number
7 is odd number
8 is even number
9 is odd number
10 is even number


# Loop Control Statements

1. break
The break statement is used to exit the loop prematurely, regardless of the loop's condition.

In [ ]:
for i in range(1,100):  #range(10)= (1 to 99)  # 0(1),..............10(9)
    if i == 10:
      print(i)
      break
    #print(number)


10


In [ ]:
for number in range(1,100):
    if number == 10:
      break
    print(number)

In [ ]:
for number in range(1,100):
    print(number)
    if number == 10:
      break


In [ ]:
for i in range(0,10): #0123456789
  if i==5:
    continue
  print(i, end=",")


0,1,2,3,4,6,7,8,9,

In [ ]:
#2. continue
#The continue statement skips the rest of the code inside the loop for the current iteration
#and moves to the next iteration

for number in range(10):  #range(0-9)
    if number % 2 ==1:   # 0 %2 ==00,2%2==0,4%2==00, 6%2==00, 8%2==00
        continue
    print(number,end="\t")


In [ ]:
for number in range(10):
    if number % 2 == 0:
        continue
    print(number)

In [ ]:
for i in range(0,10):  #0123456789
  if i>5:
    continue
    print(i,end=',')
  else:
    print(i,end=',')

0,1,2,3,4,5,

In [ ]:
#Nested For Loops:

for i in range(1,6):
  print(i)
  for j in range(i):
    print(j,end=" ")



In [ ]:
1
2 2
3 3 3
4 4 4 4
5 5 5 5 5


In [ ]:
for i in range(1,6):
  for j in range(1,6):
    if j==3:
      continue
    print(i,j)

    #

In [ ]:
for i in range(1,6):
  for j in range(1,6):
    print(i,j)
    if j==3:
      break

      #11,12,13,21,22,23

In [ ]:
for i in range(1,6):
  for j in range(1,6):
    if i==3:
      continue
    print(i,j)

In [ ]:
for i in range(1,6):
  print((5-i)*" "+i*"*")

In [ ]:
#3. else
#An else block can be added to a loop, which is executed when the loop completes normally
#(i.e., without encountering a break statement).

for number in range(5):  #
    print(number)
else:
    print("Loop finished without break")


In [ ]:
# Pattern Printing
for i in range(1, 6):#1,2,3,4,5
    for j in range(i):
        print(i, end=' ')
    print()


In [ ]:
for i in range(1,6):   #1,2,3,4
  for j in range(1, i+1): #1 ,1,2,1,2,3,1,2,3,4
    print(i,end=' ') #1
  print()



In [ ]:
for i in range(1,5):  #1,2,3,4
  print(" "*(6-i), end =" ")
  for j in range(i):   # 1,22,333,4444,555
    print(i,end=' ')
  print(" ")

  #         1
  #        2 2
  #       3 3 3
  #      4 4 4 4

In [ ]:
1
12
123
1234


In [ ]:
for i in range(1,5):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

#1
#1 2
#1 2 3
#1 2 3 4


In [ ]:
#Butterfly star pattern
for i in range(1,6):
  print(" "*(5-i)+i*"* ")
for i in range(5,0,-1):
  print(" "*(5-i)+i*"* ")

In [ ]:
for i in range(1,6):
  print(i*"* ")
for j in range(4,0,-1):
  print(j*"* ")


In [ ]:
#Pascal Triangle



In [ ]:
#Fibonacci Series



# Combining for Loop and if Statements
You can combine for loops with if statements to execute code conditionally within the loop.


In [ ]:
#Example: Filtering Even Numbers

numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

for number in numbers:
    if number % 2 == 0:
        print(number,"is even")
    else:
        print(f"{number} is odd")
# 1 is odd
#Filter Even Numbers using While Loop.

# Nested Loops
Loops can be nested inside other loops to handle more complex scenarios.

# Summary
for Loop: Used to iterate over a sequence.
while Loop: Repeats a block of code as long as a condition is true.
Loop Control Statements:
break: Exits the loop prematurely.
continue: Skips to the next iteration.
else: Executes after the loop completes normally.


# Functions
in Python are a fundamental concept that allows you to group a set of statements
so you can run them multiple times throughout your code.
Functions help make your code modular, reusable, and organized.
Let's dive into the details of functions in Python and break down every aspect of them.

#Defining a Function
A function is defined using the def keyword, followed by the function name, parentheses (), and a colon :. The body of the function contains the code that executes when the function is called.

In [ ]:
def greet():
    print("Hello, world!")

In [ ]:
def greet():
  print(" Good Morning ")
greet()

 Good Morning 


In [ ]:
def my_name():
    print("Vyankat")

In [ ]:
greet()

Hello, world!


In [ ]:
my_name()

Vyankat


In [ ]:
greet()

In [ ]:
#Function Parameters and Arguments
# Two types of functions:
# 1. User defined function   2. Built in Function
#Functions can accept parameters, which are variables passed to the function to provide input.

def greet(arg):
    print(f"Good Morning, {arg}!")
greet("Coders")

Good Morning, Coders!


In [ ]:
greet("Vyankat")

Good Morning, Vyankat!


In [ ]:
#Return Statement
#Functions can return a value using the return statement.

def multiply(a, b,c):
    return a*b*c

result = multiply(3, 5,4)
print(result)


60


In [ ]:
multiply(5,4,5)

100

# Arbitrary Arguments
- You can pass a variable number of arguments to a function using *args and **kwargs.

- Using *args for Non-Keyword Arguments

In [ ]:
def add(*args):
    return sum(args)

print(add(1, 2, 3,4,5,8))  # Output: 6
#print(add(4, 5, 6, 7))  # Output: 22


NameError: name 'a' is not defined

In [ ]:
#Using **kwargs for Keyword Arguments

#**kwargs: Collects extra keyword arguments as a dictionary.
#kwargs.items(): Iterates over key-value pairs in the dictionary.

def print_details(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_details(name="Alice", age=30, city="New York")
# Output:
# name: Alice
# age: 30
# city: New York


name: Alice
age: 30
city: New York


# Lambda Functions
Lambda functions are small anonymous functions defined with the lambda keyword.

In [ ]:
multiply = lambda a, b: a * b
print(multiply(8, 5))

40


In [ ]:
def add(a, b):
    return a + b
print(add(8, 5))

add =lambda a,b:a+b

In [ ]:
#create a function to find square of a number
Cube = lambda x: x * x * x
print(Cube(5))

125


In [ ]:
z = lambda x, y: x - y
print(z(5,6))

-1


# Python Arrays:

#Python does not have built-in support for arrays as it does with lists,
#but you can use the array module or third-party libraries like NumPy to work with arrays.

In [ ]:
#Using the array Module
#The array module provides a basic array data structure that is more efficient for numerical data compared to lists.

#Importing the array Module   #import array as arr
#First, you need to import the array module:

import array as arr

#Creating an Array
#You create an array by specifying the type code and the initial values:

Eg_array = arr.array('i', [1, 2, 3, 4, 5])

#'i': Type code for integers.
#[1, 2, 3, 4, 5]: Initial values for the array.

#You can access array elements by index:
print(Eg_array[0])  # Output: 1
print(Eg_array[2])  # Output: 3
print(Eg_array[3])  # 4

#You can modify elements by index:
Eg_array[1] = 10
print(Eg_array)  # Output: array('i', [1, 10, 3, 4, 5])

#You can add elements to the array using append and extend:
Eg_array.append(6)
print(Eg_array)  # Output: array('i', [1, 10, 3, 4, 5, 6])

Eg_array.extend([7, 8, 9])
print(Eg_array)  # Output: array('i', [1, 10, 3, 4, 5, 6, 7, 8, 9])

#You can remove elements using remove and pop:
Eg_array.remove(10)
print(Eg_array)  # Output: array('i', [1, 3, 4, 5, 6, 7, 8, 9])

Eg_array.pop()
print(Eg_array)  # Output: array('i', [1, 3, 4, 5, 6, 7, 8])


In [ ]:
import array as arr
arr = arr.array('u', ['b', 'a', 'c', 'd', 'e'])
print(arr)

array('u', 'bacde')


In [ ]:
arr.pop()
print(arr)  # Output: array('i', [1, 3, 4, 5, 6, 7, 8])

array('i', [1, 3, 4])


In [ ]:
import array

#Creating an Array
#You create an array by specifying the type code and the initial values:

arr = array.array('u',['1', '2','a', '3', '4', '5'])

#'i': Type code for integers.
#[1, 2, 3, 4, 5]: Initial values for the array.
print(arr)
#You can access array elements by index:
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3
print(arr[3])  #

array('u', '12a345')
1
a
3


# Type Codes
The array module uses type codes to specify the type of elements in the array:

- 'b': signed char  (-ve & +ve)       int     1 byte   Can represent both -ve & +ve numbers. Range: -128 to 127.
- 'B': unsigned char(+ve)       int     1 byte   Can represent only +ve numbers.    Range: 0 to 255
- 'u': Unicode character   char    2 byte   Range  65,536 characters.
- 'h': signed short        int     2 byte   Range: -32,768 to 32,767
- 'H': unsigned short      int     2 byte   Range: 0 to 65,535
- 'i': signed int          int     2 byte   Range: -32,768 to 32,767 (if 2 bytes)
- 'I': unsigned int        int     2 byte   Range: 0 to 65,535 (if 2 bytes)
- 'l': signed long         int     4 byte   Range: -2,147,483,648 to 2,147,483,647
- 'L': unsigned long       int     4 byte   Range: 0 to 4,294,967,295
- 'f': float               float   4 byte   Range: Floating point numbers (single precision)
- 'd': double              float   8 byte   Range: Floating point numbers (double precision)

In [ ]:
#Arrays:
import array as arr
arr = arr.array('B', [1,25,3, 4, 5,41,5])
print(arr)

array('B', [1, 25, 3, 4, 5, 41, 5])


In [ ]:
import array as arr
arr = arr.array('h', [-32746,-125,3, 4, 5,41,5,32127])
print(arr)

array('h', [-32746, -125, 3, 4, 5, 41, 5, 32127])


In [ ]:
import array as arr
arr = arr.array('u', ['H', 'e','l','l','o'])
print(arr)

In [ ]:
#1. append()
#Adds an element to the end of the array.
import array as arr
x = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(x)
x.append(8)
print(x)


array('i', [1, 2, 3, 4, 5, 6, 26, 5])
array('i', [1, 2, 3, 4, 5, 6, 26, 5, 8])


In [ ]:
#2. extend()
#Adds elements from an iterable (e.g., list) to the end of the array.

#import array as arr
#arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(x)

x.extend([12,14,14])
print(x)

array('i', [1, 2, 3, 4, 5, 6, 26, 5, 8])
array('i', [1, 2, 3, 4, 5, 6, 26, 5, 8, 12, 14, 14])


In [ ]:
#3. insert()
#Inserts an element at a specified position in the array.
import array as arr
#arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(x)
x.insert(4,24)
print(x)
#arr.insert(0,0)
#print(arr)

array('i', [1, 2, 3, 4, 5, 6, 26, 5, 8, 12, 14, 14])
array('i', [1, 2, 3, 4, 24, 5, 6, 26, 5, 8, 12, 14, 14])


In [ ]:
arr.insert(1,10)
print(arr)

In [ ]:
#4. pop()
#Removes and returns the last element, or the element at a specified position.
import array as arr
#arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(x)
x.pop()
print(x)
x.pop(2)
print(x)


array('i', [1, 2, 4, 24, 5, 6, 26, 5, 8, 12])
array('i', [1, 2, 4, 24, 5, 6, 26, 5, 8])
array('i', [1, 2, 24, 5, 6, 26, 5, 8])


array('i', [1, 10, 4])


In [ ]:
#5. remove()
#Removes the first occurrence of a specified element
import array as arr
#arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(x)
x.remove(5)
print(x)
x.insert(3,5)
print(x)
x.insert(5,5)

print(x)

array('i', [1, 2, 24, 5, 6, 26, 8])
array('i', [1, 2, 24, 6, 26, 8])
array('i', [1, 2, 24, 5, 6, 26, 8])
array('i', [1, 2, 24, 5, 6, 5, 26, 8])


In [ ]:
#How to find the 2nd occurance:
#We can find it by using if condition as follow:

import array as arr

# Create an array of integers
#arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
#print("Original array:", arr)

# Create a Function to remove the second occurrence of a value
def remove_second_occurrence(array, value):
    count = 0
    for elements in range(len(x)):
        if array[elements] == value:  #5
            count += 1
            if count == 2:
                array.pop(elements)
                break

# Remove the second occurrence of 5
remove_second_occurrence(x, 5)
print("Array after removing second occurrence of 5:", x)


Array after removing second occurrence of 5: array('i', [1, 2, 24, 5, 6, 26, 8])


In [ ]:
#6. index()
#Returns the index of the first occurrence of a specified element.
import array as arr
arr = arr.array('i', [1, 2, 3, 4, 5,6,26,5])
print(arr)
print(arr.index(5))

array('i', [1, 2, 3, 4, 5, 6, 26, 5])
4


In [ ]:
# Importing the array module and aliasing it as arr
import array as arr

# Creating an array of integers
arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", arr)  # Output the original array

# Defining a function to find the index of the second occurrence of a value
def find_second_occurrence_index(array, value):
    count = 0  # Initialize a counter to keep track of occurrences
    for i in range(len(array)):  # Loop through each index in the array
        if array[i] == value:  # Check if the current element matches the value
            count += 1  # Increment the counter
            if count == 2:  # Check if this is the second occurrence
                return i  # Return the index of the second occurrence
    return -1  # Return -1 if the second occurrence is not found

# Calling the function to find the index of the second occurrence of 5
index = find_second_occurrence_index(arr, 4)

# Output the index of the second occurrence
print("Index of the second occurrence of 4:", index)



In [ ]:
#7. count()
#Returns the number of occurrences of a specified element.
import array as arr

# Creating an array of integers
arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5,4,4,4])
print("Original array:", arr)

print(arr.count(4))

Original array: array('i', [1, 2, 3, 4, 5, 6, 26, 5, 4, 4, 4])
4


In [ ]:
#8. reverse()
#Reverses the order of elements in the array.

import array as arr

# Creating an array of integers
#arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", x)
x.reverse()
print("Reversed Array: ",x)
#print(arr.reverse())

Original array: array('i', [1, 2, 24, 5, 6, 26, 8])
Reversed Array:  array('i', [8, 26, 6, 5, 24, 2, 1])


In [ ]:
print(x.count(5))

1


In [ ]:
#reverse() method does not return a value; it modifies the array in place.
#Therefore, calling print(arr.reverse())
#will print None because reverse() does not have a return value.

In [ ]:
#9. buffer_info()
#Returns a tuple containing the memory address and the number of elements in the array.
import array as arr

# Creating an array of integers
#arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", x)

print(x.buffer_info())


Original array: array('i', [8, 26, 6, 5, 24, 2, 1])
(135587760168496, 7)


In [ ]:
#10. tolist()
#Converts the array to a regular list.
import array as arr

# Creating an array of integers
#arr = arr.array('i', [1, 2, 3, 4, 5, 6, 26, 5])
print("Original array:", x)
print(x.tolist())

Original array: array('i', [8, 26, 6, 5, 24, 2, 1])
[8, 26, 6, 5, 24, 2, 1]


# NumPy (Numerical Python)
    is a powerful library for numerical computations in Python.
    It provides support for arrays, matrices, and
    many mathematical functions to operate on these data structures.

In [ ]:
x =[2,4,6,8,10]
for i in x:
  print(i/2)

1.0
2.0
3.0
4.0
5.0


In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
import numpy as np
x=np.array([2,4,6,8,10])

print(x)


[ 2  4  6  8 10]


In [ ]:
x*2

array([ 4,  8, 12, 16, 20])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
#Numpy has Rich set of NumPy Functions:

## Set1 = Random Functions:

In [ ]:
import numpy as np
np.random.randint(0,10,6)   #randint will generate randopm integer numbers

array([3, 5, 5, 8, 7, 7])

In [ ]:
array=np.random.randint(0,10,(3,4))
array

array([[5, 1, 8, 4],
       [2, 7, 0, 3],
       [2, 5, 5, 3]])

In [ ]:
np.random.randint(0,10,(2,3))

array([[0, 6, 8],
       [0, 8, 3]])

In [ ]:
np.random.randint(100,200,2)   #Random Data from 0 to 1

array([127, 181])

In [ ]:
#Numpy slicing
array[1: ,0:2]


In [ ]:
x = np.array()

In [ ]:
data = np.random.randint(0,10,(5,4))
data

array([[6, 9, 0, 8],
       [2, 7, 8, 0],
       [9, 4, 4, 3],
       [1, 2, 9, 5],
       [9, 4, 6, 0]])

In [ ]:
data[1: , :2]

#

array([[0, 1],
       [9, 5],
       [5, 6],
       [5, 6]])

In [ ]:
data[2:4,1: ]

array([[5, 2, 4],
       [6, 1, 2]])

In [ ]:
data [2:4,1: ]

In [ ]:
#Numpy

#1 D array:

import numpy as np
a=np.array([1,23,24])
print(a)

[ 1 23 24]


In [ ]:

import numpy as np

#1D array
a =np.array([2,3,4])
print(a)

[2 3 4]


In [ ]:
#2D array

b=np.array([[2,4,6],[8,10,12],[5,6,7]]),([[1,7,3],[5,5,6],[5,8,7]])
print(b)


(array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 5,  6,  7]]), [[1, 7, 3], [5, 5, 6], [5, 8, 7]])


In [ ]:
#3 D Array

#2D array

c=np.array([[2,4,6],[8,10,12],[5,3,4]])
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [ 5  3  4]]


In [ ]:
#Initialize Numpy arrays

#initialize 'x X y' dimensions with '0' values
import numpy as np
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np

#full array with -6 values
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
import numpy as np

In [ ]:
#1D Array

a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2D Array

In [ ]:
a =np.array([[2,4,6],[4,5,6],[6,5,7]])

print(a)
print(type(a))
a.ndim

[[2 4 6]
 [4 5 6]
 [6 5 7]]
<class 'numpy.ndarray'>


2

In [ ]:
x= np.array([[[1,2,3], [4,5,6],[5,6,7]], [[4,5,6],[8,8,7],[8,9,7]]])
print(x)

print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[4 5 6]
  [8 8 7]
  [8 9 7]]]
<class 'numpy.ndarray'>


3

In [ ]:
#Initialize Array:

#Initilize an array of 'x' X 'y' dimensions with 0

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Initilize an array of 'x' X 'y' dimensions with 1

b=np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Initilize 'x' and 'y' with an interval of z

np.arange(0,101,10) #

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
#initialize 'z' numbers between 'x' and 'y'
#devide upper and lower limit to equal measures

np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace(9,90,10)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90.])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(5)  # eye: refer to identical matrix

In [ ]:
np.eye(3)

In [ ]:
np.eye(8)

In [ ]:
data

NameError: name 'data' is not defined

In [ ]:
import numpy as np

# Create the NumPy array
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])

# Print the array
print(data)


In [ ]:
dt =[1,3,4]
sum(dt)

8

In [ ]:
data.max()

np.int64(12)

In [ ]:
data.mean()

np.float64(6.0)

In [ ]:
data.sum()

np.int64(120)

In [ ]:
#Fill SAME numbers in an array of dimensions 'x' X 'y'

np.full((4,5),3)

In [ ]:
#ndarray.shape:

a=np.array([[2,4,6],[5,6,7],[8,10,12]])
print(a)
print(a.shape)

[[ 2  4  6]
 [ 5  6  7]
 [ 8 10 12]]
(3, 3)


In [ ]:
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)   #2,3

In [ ]:
#We can use ndarray.shape function to resize the array:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]]) #3,4 =12
print("Original Array:\n", a)
a.shape=(6,2)   #12 = 1,2,3,4,6,12 (1,12), (2,6),(3,4),(4,3),(6,2)(12,1)
print("Changed Array:\n",a)

a.shape=(4,3)
print("Changed Array:\n",a)

Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
b.shape=(6,1)  # 12= 1*12,2*6,3*4, 4*3,6*2,1*12
print(b)
#print(b.size)
print(b.ndim)

[[1 2 3]
 [4 5 6]
 [5 8 8]
 [5 6 4]]
2


In [ ]:
z=np.arange(24)
print(z)
#1D array[0,1,2,3,.....,23]  # 1*24
#print(z)     #24 =1,2,3,4,6,8,12,24(1,24)(2,12),(3,8)
# For reshaping into 3D Array (2,6,2) (4,2,3)
z.shape=(2,3,4)  #4,3,2
#3 dimensional
print(z)
print(z.ndim)  #.ndim= no of dimenssions in that array

In [ ]:
z=np.arange(30)
#print(z)
#1D array[0,1,2,3,.....,23]  # 1*24
#print(z)     #24 =1,2,3,4,6,8,12,24(1,24)(2,12),(3,8)
# For reshaping into 3D Array (2,5,3),(3,5,2),(1,10,3)
z.shape=(1,10,3)  #2,2,2,3
#3 dimensional
print(z)
print(z.ndim)

In [ ]:
Y =np.arange(200)  #0,1,.......,199
#print(Y)
#print(Y.size)    #200 =100*2 =50*2*2=25*2*2*2=5*5*2*2*2


Y.shape=(4,2,5,5) #5*5*4*2
print(Y)
print(Y.ndim)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]
   [ 20  21  22  23  24]]

  [[ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]
   [ 40  41  42  43  44]
   [ 45  46  47  48  49]]]


 [[[ 50  51  52  53  54]
   [ 55  56  57  58  59]
   [ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]]

  [[ 75  76  77  78  79]
   [ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]]


 [[[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]
   [120 121 122 123 124]]

  [[125 126 127 128 129]
   [130 131 132 133 134]
   [135 136 137 138 139]
   [140 141 142 143 144]
   [145 146 147 148 149]]]


 [[[150 151 152 153 154]
   [155 156 157 158 159]
   [160 161 162 163 164]
   [165 166 167 168 169]
   [170 171 172 173 174]]

  [[175 176 177 178 179]
   [180 181 182 183 184]
   [185 186 187 188 189]
   [190 191 192 193 194]
   [1

In [ ]:
import numpy as np
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)
print(b.ndim)
#Convert above array into 2D and 3D array
b.shape=(3,2)

print(b)#6=1,2,3,6

(2, 3)
2
[[ 4  5]
 [ 6  6]
 [ 8 10]]


In [ ]:
#Addition Using numpy Function

np.multiply(10,20)

In [ ]:
np.sum([20,10,3])

In [ ]:
#Add the arrays
#axis=0 will add numbers by Columns
#axis =1 will add numbers by rows
np.sum([[0,1],[0,5],[3,5]],axis = 0)
#np.sum([[0,1],[0,5],[3,5]],axis = 1)



In [ ]:
#axis=1 will add numbers by rows

np.sum([[0,1],[0,5],[3,5]],axis = 1)



In [ ]:
data

In [ ]:
data.sum(axis=1)

In [ ]:
data.sum(axis=0)

In [ ]:
data.min(axis=0)

In [ ]:
data.argmin(axis=0)

In [ ]:
data.max(axis=1)

In [ ]:
data.mean()


#Metrix in Data/Basic Descriptive Statiestics
1.min
2.max
3.mean
4.Mode
5. Median
6. Standard Deviation
7. Count
8. Q1, Q2, Q3, Q4
```



In [ ]:
a= np.array([3,4])
b=np.array([5,6])

print(np.sum((a,b), axis=0))
print(np.sum((a,b), axis=1))


In [ ]:
#Array comparions

#Element wise Comparison.. fun called as equal
import numpy as np

a=[1,2,4]
b=[2,4,4]
c=[1,2,4]

print(np.equal(a,b)) #False,False,True
print(np.equal(a,c))

In [ ]:
#Array wise comparison
import numpy as np

a=[1,2,4]
b=[2,4,4]
c=[1,2,4]

print(np.array_equal(a,b))  #
print(np.array_equal(a,c))  #

In [ ]:
import numpy as np
d = np.array(24)
print(d)

In [ ]:
d=np.arange(24)  #24 =12*2 , 6*4, 8*3
print(d)

In [ ]:
d.shape=(12,2)
print(d)

# Find the number Elements in array

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size )   #
print(a.shape)   #
print(a.ndim)
print(a.dtype)
#

In [ ]:
a=np.array([
    [[1,2,3,4],[4,5,6,8]],
     [[7,8,9,4],[4,5,5,6]]
])
print(a.size)
print(a.dtype)

import numpy as np



print(a.shape)  # Output: (2, 2, 4)
print(a.ndim)   # Output: 3


# Finding the data type of an array

In [ ]:
print(a.dtype)

In [ ]:
d=np.arange(24)  #[0,-----,23]
print(d)
print(d.dtype)

In [ ]:
d=np.arange(24,dtype='float') #0,1,.....,23
print(d)
print(d.dtype)

I# Numpy array Mathematics- Sum

In [ ]:
import numpy as np
np.sum([10,30,60,54,68,258])

np.int64(480)

In [ ]:
a=[10,20]   #25+30
b=[20,5]

np.sum([a,b])

np.int64(55)

In [ ]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],       #[8,10,12],[14,16,18]
                   [10, 11, 12]])

array3 = np.array([[8, 6, 9],      #[16,16,21],[24,25,31]
                   [10, 9, 13]])

# Adding the two arrays
sum_array = array1+array2+array3
print("Addition:\n", sum_array)
sum_array.ndim

# Subtraction:

In [ ]:
import numpy as np

np.subtract(10,20)

np.int64(-10)

In [ ]:
 #Subtraction of two arrays:

a=np.array([0,1,6])
b=np.array([0,5,3])
c=np.array([0,1,2])
Sub = a-b-c
print(Sub)

[ 0 -5  1]


In [ ]:
a=[0,1]
b=[0,5]

np.subtract(a,b)

In [ ]:
import numpy as np

a = np.array([[2, 4],
              [5,8]])
b = np.array([[4, 6],
              [3,5]])

# Perform element-wise subtraction
result = np.subtract(a, b)
print("Result of a - b:", result)  #


In [ ]:
#Using Different Shapes(Broadcasting)
import numpy as np

a = np.array([[1, 2],[6, 8],[6,5]])
b = np.array([5,4])

# Addition from each row of a using broadcasting
result = a + b
print("Result of a + b with broadcasting:\n", result)


Result of a + b with broadcasting:
 [[ 6  6]
 [11 12]
 [11  9]]


In [ ]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Subtracting the second array from the first array
difference_array = array1 - array2
print("Subtraction:\n", difference_array)


# Multiplication of Numpy Array:

In [ ]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Multiplying the two arrays element-wise
product_array = array1 * array2
print("Multiplication:\n", product_array)


Multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [ ]:
array1 = np.array([[1, 2,3],
                   [4, 5,3],
                   [4,6,1]])

array2 = np.array([[7, 8],
                  [4,1],
                   [5,2]
                   ])

# Multiplying the two arrays element-wise
product_array = array1 * array2
print("Multiplication:\n", product_array)

#Matrix Multiplication:
the number of columns in the first matrix must be equal to the number of rows in the second matrix. The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix. The product of matrices A and B is denoted as AB.

In [ ]:
m*n, n*k      =

In [ ]:
x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))

In [ ]:
x1

array([[8, 6],
       [7, 1]])

In [ ]:
x2

array([[8, 9],
       [4, 5]])

In [ ]:
np.dot(x1,x2)

array([[ 88, 102],
       [ 60,  68]])

In [ ]:
x1=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(2,2))

In [ ]:
x1

array([[4, 3, 3],
       [3, 6, 8]])

In [ ]:
x2

array([[7, 8],
       [5, 7]])

#String Functions


In [ ]:
x=np.array([1,2,3,'data'])

In [ ]:
x

array(['1', '2', '3', 'data'], dtype='<U21')

In [ ]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U21')

In [ ]:
np.char.center(x,10,fillchar='-')

array(['----1-----', '----2-----', '----3-----', '---data---'],
      dtype='<U10')

In [ ]:
x=np.array([1,2,3,'data eNginEerIng'])

In [ ]:
x

array(['1', '2', '3', 'data engineering'], dtype='<U21')

In [ ]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))

In [ ]:
np.char.split(x)

In [ ]:
y=np.array(["Data Science","Machine Learning"])

In [ ]:
np.char.split(y,sep='e')

array([list(['Data Sci', 'nc', '']), list(['Machin', ' L', 'arning', ''])],
      dtype=object)

In [ ]:
np.char.count(y,"i")

array([1, 2])

In [ ]:
y

array(['Data Science', 'Machine Learning'], dtype='<U16')

In [ ]:
np.char.startswith(y, "M")

In [ ]:
np.char.replace(y,'a','xxxxxxx')

In [ ]:
np.char.rjust(y,20,fillchar="*")

array(['********Data Science', '****Machine Learning'], dtype='<U20')

In [ ]:
np.char.ljust(y,20,fillchar="*")

array(['Data Science********', 'Machine Learning****'], dtype='<U20')

#Time Base Functions:
- YYYY:MM:DD  HH:MM:SS  Time Stamp
- YYYY:MM:DD   Date
- HH:MM:SS      Time

#Purpose:
- extract month and identify
- can be found answers questions based on time series
- extracting yeras, week, days, studied




# Division of Arrays:



In [ ]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[3, 4, 5],
                   [10, 5, 3]])

# Dividing the first array by the second array element-wise
division_array = array1 / array2
print("Division:\n", division_array)
print(division_array.dtype)

Division:
 [[ 3.33333333  5.          6.        ]
 [ 4.         10.         20.        ]]
float64


# Calculating the Exponential:

This line calculates the exponential of each element in the array a.
The function np.exp() applies the exponential function
𝑒^a
  to each element in the array.
  

In [ ]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 2, 3, 4, 5])

# Calculating the exponential of each element in the array
exp_a = np.exp(a)

print("Original array:", a)
print("Exponential of the array:", exp_a)  #e = 2.718281828459045


Original array: [1 2 3 4 5]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
import math
math.e

2.718281828459045

In [ ]:
#Exponential of a 2D Array


import numpy as np

# Creating a 2D NumPy array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Calculating the exponential of each element in the 2D array
exp_b = np.exp(b)

print("Original 2D array:\n", b)
print("Exponential of the 2D array:\n", exp_b) #e^1,


# Square Root (np.sqrt())
The np.sqrt() function computes the non-negative square root of each element in the input array.

In [ ]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 4, 9, 16, 25,37])

# Calculating the square root of each element
sqrt_a = np.sqrt(a)

print("Original array:", a)  #[1,4,9,16,25]
print("Square root of the array:", sqrt_a)  #[1.,2.,3.,4.,5.]


In [ ]:
#expo, sqrt,sin,cos,log

a=np.array([2,4,6])

print("sqrt of a:", np.sqrt(a))
print("exp of a:", np.exp(a))
print("sin of a:", np.sin(a))
print("cos of a:", np.cos(a))
print("log of a:", np.log(a))

In [ ]:
#Aggregate Functions:

#aggregate functions perform computations on arrays to return a single value.
#Here are some common aggregate functions in NumPy

a=np.array([1,2,4,5,6,7,8,9])
print("Sum:",np.sum(a))   # 42
print("Minimum Value:", np.min(a))   #1
print("Mean Value:", np.mean(a))     #mean =average
print("Median Value:", np.median(a)) #
print("Corelation Coefficient:", np.corrcoef(a))   #
print("Standard Deviation:", np.std(a))      #


Sum: 42
Minimum Value: 1
Mean Value: 5.25
Median Value: 5.5
Corelation Coefficient: 1.0
Standard Deviation: 2.6339134382131846


In [ ]:
#Data Maipulation Method:

In [ ]:
import numpy as np
x= np.random.randint(0,10,(4,6))
print(x)

In [ ]:
np.split(x,2,axis=0)  #It will split list into 2 parts

In [ ]:
np.split(x,2,axis=1) #split into vertical parts

In [ ]:
np.split(x,4,axis=0)

In [ ]:
np.vsplit(x,2)

In [ ]:
np.hsplit(x,2)

In [ ]:
x.T  #Transpose- It will swap rows to column and column to rows

In [ ]:
x=np.random.randint(0,10,(2,2))
print(x)

In [ ]:
y=np.random.randint(0,10,10)
y

array([2, 5, 2, 1, 7, 9, 1, 6, 2, 7])

In [ ]:
np.quantile(y,0.25)

In [ ]:
np.quantile(y,0.50)

In [ ]:
np.median(x)

In [ ]:
np.quantile(y,0.75)

In [ ]:
#Arithmetic Function
#Data Maniulation
# Descriptive Functions


# Numpy Broadcasting

In [ ]:
import numpy as np

a = np.array([1, 2.5, 3])
b = 2
c = a + b
print(c)


[3.  4.5 5. ]


In [ ]:
# Broadcasting with Different Shapes

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 0, 1])
c = a + b
print(c)



In [ ]:
#Higher Dimensions

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6],[2,4,5]])
b = np.array([1])
#d=np.array([[2,3,4],[4,8,9]])
c = a + b
print(c)


# Indexing and Slicing in Python:

In [ ]:
import numpy as np
a =np.array([[1,2,3],[4,5,6],[7,8,9]])  # Array
          #     0       1       2
          #   0  1 2  0  1 2   0 1 2
print(a[0:1,1:2]) #2
print(a[ :1,1: ])  #2,3
print(a[1:2,1: ])  #5,6
print(a[2: ])     #7,8,9

#print 4,5,6 from 1st index

In [ ]:
print(a[ :2,1: ])

In [ ]:
#print(a[ :2,0:2])
print(a[1:2,1: ])

In [ ]:
print(a[ :3,1: ])

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
import numpy as np

x=np.random.randint(0,20,(6,5))
print(x)

[[10  9  6  0 18]
 [19 15  8 18 13]
 [10 13 15 13  8]
 [13 17 16  5 13]
 [ 5 11  6 19  1]
 [ 5 14 19  1  6]]


In [ ]:
x.shape=(2,15)   #30=1*30, 2*15,3*10,5*6,10*3,15*2,30*1
print(x)

[[10  9  6  0 18 19 15  8 18 13 10 13 15 13  8]
 [13 17 16  5 13  5 11  6 19  1  5 14 19  1  6]]


In [ ]:
x.ravel()   #ravel flattens the array


array([10,  9,  6,  0, 18, 19, 15,  8, 18, 13, 10, 13, 15, 13,  8, 13, 17,
       16,  5, 13,  5, 11,  6, 19,  1,  5, 14, 19,  1,  6])

In [ ]:
x.reshape(3,10)


array([[ 9,  0,  5, 14,  1, 10,  3, 17, 10,  5],
       [ 6, 14,  7, 14,  8,  2, 13, 12,  9,  6],
       [10, 18, 19,  8,  8,  7, 16, 15, 11,  2]])

In [ ]:
print(x)

[[ 9  0  5 14  1]
 [10  3 17 10  5]
 [ 6 14  7 14  8]
 [ 2 13 12  9  6]
 [10 18 19  8  8]
 [ 7 16 15 11  2]]


In [ ]:
y.reshape(10,3)

print(x)

[[ 9  0  5 14  1]
 [10  3 17 10  5]
 [ 6 14  7 14  8]
 [ 2 13 12  9  6]
 [10 18 19  8  8]
 [ 7 16 15 11  2]]


In [ ]:
y.reshape(5,6)

In [ ]:
x1 =np.array([[2,3],[4,3]])
print(x1)

In [ ]:
x2= np.array([[4,5],[6,7]])
print(x2)

In [ ]:
np.vstack([x1,x2])

In [ ]:
np.hstack([x1,x2])

In [ ]:
np.concatenate([x1,x2],axis=0)  #vstack

In [ ]:
np.concatenate([x1,x2],axis=1)   #hstack

In [ ]:
x=np.random.randint(0,10,(4,6))
x

array([[4, 7, 7, 5, 1, 3],
       [4, 6, 5, 6, 7, 1],
       [7, 2, 0, 2, 1, 4],
       [6, 9, 6, 4, 5, 3]])

In [ ]:
np.split(x,2,axis=0)

[array([[4, 7, 7, 5, 1, 3],
        [4, 6, 5, 6, 7, 1]]),
 array([[7, 2, 0, 2, 1, 4],
        [6, 9, 6, 4, 5, 3]])]